# Generated by Django 5.1.5 on 2025-01-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('thread_id', models.IntegerField(blank=True, null=True)),
                ('checkpoint_ns', models.TextField(default='')),
                ('checkpoint_id', models.TextField(primary_key=True, serialize=False)),
                ('parent_checkpoint_id', models.TextField(blank=True, null=True)),
                ('type', models.TextField()),
                ('checkpoint', models.BinaryField(blank=True, null=True)),
                ('metadata', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DjCheckpoint',
        ),
    ]
