# Generated by Django 5.1.5 on 2025-01-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_checkpoint_delete_djcheckpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
