# Generated by Django 5.1.5 on 2025-01-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_thread_threadmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadmessage',
            name='response',
            field=models.TextField(default='.'),
            preserve_default=False,
        ),
    ]
